// Generated by 'unplugin-auto-import'
export {}
declare global {
  const nprogress: typeof import('./src/components/nprogress')['default']
}
// for vue template auto import
import { UnwrapRef } from 'vue'
declare module 'vue' {
  interface ComponentCustomProperties {
    readonly nprogress: UnwrapRef<typeof import('./src/components/nprogress')['default']>
  }
}
