// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ElAside: typeof import('element-plus/es')['ElAside']
    ElButton: typeof import("element-plus/es")["ElButton"]
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElForm: typeof import("element-plus/es")["ElForm"]
    ElFormItem: typeof import("element-plus/es")["ElFormItem"]
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import("element-plus/es")["ElInput"]
    ElMain: typeof import('element-plus/es')['ElMain']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElRow: typeof import("element-plus/es")["ElRow"]
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTabPane: typeof import("element-plus/es")["ElTabPane"]
    ElTabs: typeof import("element-plus/es")["ElTabs"]
    IconDark: typeof import('./src/components/icons/IconDark.vue')['default']
    IconLight: typeof import('./src/components/icons/IconLight.vue')['default']
    IEpExpand: typeof import('~icons/ep/expand')['default']
    IEpFold: typeof import('~icons/ep/fold')['default']
    IEpLoading: typeof import('~icons/ep/loading')['default']
    IEpUser: typeof import('~icons/ep/user')['default']
    IIngotAuthority: typeof import("~icons/ingot/authority")["default"]
    IIngotUser: typeof import('~icons/ingot/user')['default']
    InAppBar: typeof import('./src/components/layout/InAppBar.vue')['default']
    InAppLayout: typeof import('./src/components/layout/InAppLayout.vue')['default']
    InBaseContainer: typeof import("./src/components/InBaseContainer.vue")["default"]
    InContainer: typeof import('./src/components/InContainer.vue')['default']
    InFilterContainer: typeof import('./src/components/InFilterContainer.vue')['default']
    InIcon: typeof import('./src/components/InIcon.vue')['default']
    InMenu: typeof import('./src/components/layout/InMenu.vue')['default']
    InMenuToggle: typeof import('./src/components/layout/InMenuToggle.vue')['default']
    InSidebarItem: typeof import('./src/components/layout/InSidebarItem.vue')['default']
    InSidebarMenu: typeof import('./src/components/layout/InSidebarMenu.vue')['default']
    InSpacer: typeof import('./src/components/InSpacer.vue')['default']
    InSubmenu: typeof import('./src/components/layout/InSubmenu.vue')['default']
    InSubMenu: typeof import('./src/components/layout/InSubMenu.vue')['default']
    InSwitchDark: typeof import('./src/components/InSwitchDark.vue')['default']
    InUserDropdown: typeof import('./src/components/user-dropdown/InUserDropdown.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
