// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AppBar: typeof import('./src/components/AppBar.vue')['default']
    AppLayout: typeof import('./src/components/AppLayout.vue')['default']
    BaseContainer: typeof import('./src/components/BaseContainer.vue')['default']
    Container: typeof import("./src/components/Container.vue")["default"]
    ElButton: typeof import('element-plus/es')['ElButton']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElRow: typeof import("element-plus/es")["ElRow"]
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    FilterContainer: typeof import('./src/components/FilterContainer.vue')['default']
    HelloWorld: typeof import("./src/components/HelloWorld.vue")["default"]
    IconCommunity: typeof import('./src/components/icons/IconCommunity.vue')['default']
    IconDark: typeof import('./src/components/icons/IconDark.vue')['default']
    IconDocumentation: typeof import('./src/components/icons/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./src/components/icons/IconEcosystem.vue')['default']
    IconLight: typeof import('./src/components/icons/IconLight.vue')['default']
    IconSupport: typeof import('./src/components/icons/IconSupport.vue')['default']
    IconTooling: typeof import('./src/components/icons/IconTooling.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SwitchDark: typeof import('./src/components/SwitchDark.vue')['default']
  }
}
